---
- name: Install_redhat | Install RPM keys
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "{{ vscodium_rpm_gpg_key }}"

- name: Install_redhat | Setup vscodium repository
  become: true
  ansible.builtin.yum_repository:
    state: present
    file: vscodium
    description: gitlab.com_paulcarroty_vscodium_repo
    name: download.vscodium.com
    baseurl: https://download.vscodium.com/rpms/
    enabled: 1
    async: true
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: "{{ vscodium_rpm_gpg_key }}"
    owner: root
    group: root
    mode: '0644'
